export const catalog = [
  { slug: "accordion", name: "Accordion", states: ["Default", "Open", "Multiple", "Disabled"] },
  { slug: "alert", name: "Alert", states: ["Default", "Destructive"] },
  { slug: "alert-dialog", name: "Alert dialog", states: ["Default", "Small"] },
  { slug: "aspect-ratio", name: "Aspect ratio", states: ["16:9", "4:3", "Square"] },
  { slug: "attachment", name: "Attachment", states: ["States", "Sizes", "Vertical"] },
  { slug: "avatar", name: "Avatar", states: ["Sizes", "Group", "Badge"] },
  { slug: "badge", name: "Badge", states: ["Variants"] },
  { slug: "breadcrumb", name: "Breadcrumb", states: ["Default", "Collapsed"] },
  { slug: "bubble", name: "Bubble", states: ["Variants", "Alignment", "Reactions"] },
  { slug: "button", name: "Button", states: ["Variants", "Sizes", "Icon", "Disabled", "Loading"] },
  { slug: "button-group", name: "Button group", states: ["Horizontal", "Vertical"] },
  { slug: "calendar", name: "Calendar", states: ["Single", "Range", "Disabled dates"] },
  { slug: "card", name: "Card", states: ["Default", "Small"] },
  { slug: "carousel", name: "Carousel", states: ["Single", "Multiple"] },
  { slug: "chart", name: "Chart", states: ["Bar", "Line", "Area"] },
  { slug: "checkbox", name: "Checkbox", states: ["States", "Disabled", "Invalid"] },
  { slug: "collapsible", name: "Collapsible", states: ["Closed", "Open", "Disabled"] },
  { slug: "combobox", name: "Combobox", states: ["Default", "Selected", "Disabled"] },
  { slug: "command", name: "Command", states: ["Default", "Empty"] },
  { slug: "context-menu", name: "Context menu", states: ["Default", "Checkbox items"] },
  { slug: "dialog", name: "Dialog", states: ["Default", "Form"] },
  { slug: "direction", name: "Direction", states: ["Left to right", "Right to left"] },
  { slug: "drawer", name: "Drawer", states: ["Bottom", "Right", "Snap points"] },
  { slug: "dropdown-menu", name: "Dropdown menu", states: ["Default", "Checkbox items"] },
  { slug: "empty", name: "Empty", states: ["Default", "With action"] },
  { slug: "field", name: "Field", states: ["Default", "Invalid", "Disabled", "Horizontal"] },
  { slug: "hover-card", name: "Hover card", states: ["Bottom", "Top"] },
  { slug: "input", name: "Input", states: ["Default", "Filled", "Disabled", "Invalid", "Types"] },
  { slug: "input-group", name: "Input group", states: ["Prefix", "Suffix", "Button"] },
  { slug: "input-otp", name: "Input OTP", states: ["Empty", "Filled", "Disabled"] },
  { slug: "item", name: "Item", states: ["Variants", "Sizes"] },
  { slug: "kbd", name: "Kbd", states: ["Single", "Combination"] },
  { slug: "label", name: "Label", states: ["Default", "Disabled"] },
  { slug: "marker", name: "Marker", states: ["Variants"] },
  { slug: "menubar", name: "Menubar", states: ["Default", "Checkbox items"] },
  { slug: "message", name: "Message", states: ["Received", "Sent", "Conversation"] },
  { slug: "message-scroller", name: "Message scroller", states: ["Conversation", "Long list"] },
  {
    slug: "native-select",
    name: "Native select",
    states: ["Default", "Small", "Disabled", "Invalid"],
  },
  { slug: "navigation-menu", name: "Navigation menu", states: ["Default"] },
  { slug: "pagination", name: "Pagination", states: ["Default", "With ellipsis"] },
  { slug: "popover", name: "Popover", states: ["Bottom", "Top", "Right", "Left"] },
  { slug: "progress", name: "Progress", states: ["Values", "With label", "Indeterminate"] },
  { slug: "questionnaire", name: "Questionnaire", states: ["Single choice", "Multiple choice"] },
  { slug: "radio-group", name: "Radio group", states: ["Default", "Disabled", "Invalid"] },
  { slug: "resizable", name: "Resizable", states: ["Horizontal", "Vertical"] },
  { slug: "scroll-area", name: "Scroll area", states: ["Vertical", "Horizontal"] },
  {
    slug: "select",
    name: "Select",
    states: ["Default", "Selected", "Small", "Disabled", "Invalid"],
  },
  { slug: "separator", name: "Separator", states: ["Horizontal", "Vertical"] },
  { slug: "sheet", name: "Sheet", states: ["Right", "Left", "Top", "Bottom"] },
  { slug: "sidebar", name: "Sidebar", states: ["Default", "Active item"] },
  { slug: "skeleton", name: "Skeleton", states: ["Text", "Card", "Avatar"] },
  { slug: "slider", name: "Slider", states: ["Single", "Range", "Disabled", "Vertical"] },
  { slug: "spinner", name: "Spinner", states: ["Sizes", "With label"] },
  { slug: "switch", name: "Switch", states: ["States", "Small", "Disabled"] },
  { slug: "table", name: "Table", states: ["Default", "Selected", "Empty"] },
  { slug: "tabs", name: "Tabs", states: ["Default", "Line", "Vertical", "Disabled"] },
  { slug: "textarea", name: "Textarea", states: ["Default", "Filled", "Disabled", "Invalid"] },
  { slug: "toast", name: "Toast", states: ["Types", "With action"] },
  { slug: "toggle", name: "Toggle", states: ["States", "Outline", "Sizes", "Disabled"] },
  {
    slug: "toggle-group",
    name: "Toggle group",
    states: ["Single", "Multiple", "Outline", "Disabled"],
  },
  { slug: "tooltip", name: "Tooltip", states: ["Top", "Right", "Bottom", "Left"] },
] as const;

export type ComponentSlug = (typeof catalog)[number]["slug"];
export type ComponentDoc = (typeof catalog)[number];
